### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/community-calls#1]
### Who is the audience?
_Who might want to know this? What other groups or organizations might be interested?_
- people writing R packages or scripts, or training others to do this

### Why is this important?
Since many people in the rOpenSci community are not software developers from the start, it helps to know what testing is and why and how to do it. 

paraphrased from @richfitz: Testing and automation are critical but the community in large bolts testing on afterwards, which rarely leads to a very satisfying level of testing or a process of adding it.

### What should be covered?
- test driven development & test mocking
- what works well for a predominantly data focussed domain scientist is different to what works for someone working on library code used by thousands of users

### Suggested speakers or contributors
- @richfitz has agreed to speak (he suggested the topic)
- Rich suggests also getting someone who has just recently got started with testing (say within the last ~18 months, or someone with the perspective of Charles T. Gray in her post below) and perhaps all the way down the other end - someone like Craig Citro from Google to talk about how massive orgs test.

### Resources you would recommend to the audience
- [An Ode to Testing, my first review](https://ropensci.org/blog/2018/03/13/ode-to-testing/), by Charles T. Gray

**Comment by stefaniebutland** [comment]
Suggested speakers - [Heather Turner](https://github.com/hturner) has taught this in workshops

**Comment by maelle** [comment]
[Packages for Testing your R Package](https://itsalocke.com/blog/packages-for-testing-your-r-package/)

**Comment by lopierra** [comment]
I've never done any testing before, but I keep hearing about and would like to know how to get started. Is testing only for packages, or can it be used to improve code that's not part of a package? When do you do it? Thanks.

**Comment by stefaniebutland** [comment]
Thank you for your comment @lopierra. I'll post here when we have a date set for this Community Call. Hope you can attend to learn more!

**Comment by stefaniebutland** [comment]
More resources
- rOpenSci dev guide, by editorial team, [Chapter 1.10 Testing](https://devguide.ropensci.org/building.html#testing)
- R Packages, by Hadley Wickham and Jenny Bryan, [Chapter 10 Testing](https://r-pkgs.org/tests.html)

**Comment by maelle** [comment]
[Blog post about mocking](https://blog.r-hub.io/2019/10/29/mocking/) 😇

**Comment by stefaniebutland** [comment]
[Steffi LaZerte](https://ropensci.org/authors/steffi-lazerte/) has agreed to present 🎉

**Comment by stefaniebutland** [comment]
This Community Call happening Thurs Dec 5, 2019. Read the announcement blog post for details: [Last Night, Testing Saved my Life](https://ropensci.org/blog/2019/11/12/commcall-dec2019/)

**Comment by stefaniebutland** [comment]
What’s your story? 
- What motivated you to start testing?
- What do you wish your past-self knew?
- What are your favorite resources on the topic?
- What questions do you have?

Tell us in the [pre-Call discussion](https://discuss.ropensci.org/t/community-call-on-testing-dec-5-2019-tell-us-what-you-wish-your-past-self-knew/1877)

**Comment by stefaniebutland** [comment]
Video, collaborative notes, speakers’ slides from this Community Call are posted https://ropensci.org/commcalls/2019-12-05/
