### ISSUE TITLE
Workflows that pull together ‘the best’ of reproducibility

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/community-calls#13]
Integrating tools like [targets and tarchetypes](https://github.com/ropensci/software-review/issues/401), [drake](https://docs.ropensci.org/drake/), [renv](https://rstudio.github.io/renv/), etc 

Thanks to a community member for suggesting this.

### Suggested speakers or contributors
Package authors plus users presenting use cases

**Comment by stefaniebutland** [comment]
Use of docker to enhance reproducibility #12 maybe relevant

Nüst et al, 2020. The Rockerverse: Packages and Applications for Containerisation with R
https://doi.org/10.32614/RJ-2020-007

**Comment by maelle** [comment]
[orderly package](https://www.vaccineimpact.org/orderly/) by @richfitz et al.

**Comment by stefaniebutland** [comment]
An [Openscapes](https://www.openscapes.org/) convo among researchers talking about workflows & targets pkg has me thinking it would be valuable to have people share their targets workflows for specific applications so that others could learn from different examples. Maybe like our community call on [Research Applications of rOpenSci Taxonomy and Biodiversity Tools](https://ropensci.org/commcalls/2019-03-27/) where folks take a few mins to share their examples.

**Comment by maelle** [comment]
This reminds me of a tweet I saw yesterday: https://twitter.com/lingtax/status/1443452866115506176

**Comment by maelle** [comment]
[Forum discussion "Workflow best practices"](https://discuss.ropensci.org/t/workflow-best-practices/2718/)

**Comment by yabellini** [comment]
We did: https://ropensci.org/commcalls/jan2023-targets/ that is related with this topic.
