### ISSUE TITLE
subtitles in community calls video

### ISSUE THREAD

**Issue by complexgenome** [ropensci-org/community-calls#14]
Hi ropenSci,

I'm watching useful videos available on the ropensci community calls. Is there a way these videos could have subtitles once they are uploaded? I suggest so, as rewinding doesn't help what was said during presentation. Maybe it is due to voice/mic.

**Comment by stefaniebutland** [comment]
Hi @sariya. Subtitles will absolutely improve the accessibility of our Community Calls. This has been on my mind. I need to add it to my to-do list to find out the best way to add subtitles/transcript without adding too much time to the workflow.

Thank you for suggesting this.

**Comment by Bisaloo** [comment]
What about community captioning? Using something such as https://amara.org/

**Comment by stefaniebutland** [comment]
I've enabled automatic audio transcription for next call. Will see how useful that is for potential community captioning with amara (community captioning seems like a lot of work!).

**Comment by stefaniebutland** [comment]
The [Community Call video and transcript are now on amara.org](https://amara.org/en/videos/9ay07S2E2vRe/info/maintaining-an-r-package-ropensci-community-call/?tab=video).

I spent a full day 1) figuring it out 2) editing the transcript to sync with video start 3) doing basic editing of the introduction, and learned, as expected, that this is non-trivial work. (I saved a copy of the edited transcript.)

It now needs a fair bit of editing before I would add the subtitles to our video of the Call [on vimeo](https://vimeo.com/399048757). 
- to correct panelists' names, "rOpenSci", "R", and other technical terms
- to review/edit subtitles text to match speakers' words
- to edit subtitles to follow guidelines of not-too-long or -short (the amara editing interface helps with this)
  - long subtitles cover up the video!

If editing gets completed by someone in the community, I could do a final review and copy the subtitles file to the official video of the Call. 

Could take similar approach for future calls.

**Comment by stefaniebutland** [comment]
Is this something any of you @Bisaloo @Reykt @sariya are familiar with and has time/interest to do it (no obligation!)? Or shall I put out a request to the community?

**Comment by Bisaloo** [comment]
I've done it on youtube before but I've never tried amara. But it seems quite similar so I can give it a go.

cc @Rekyt

**Comment by Rekyt** [comment]
Thank you @stefaniebutland for all this!
I've actually never done something like this, but I would like to test. I am unsure about the amount of the work needed but I would like to try at least for this video.

**Comment by stefaniebutland** [comment]
That's generous of you both. Please make note of how much time you spend on it so I can decide what's needed for future Community Calls.

I'm happy to have a short video chat with you once you've had a look at the interface and content, if you have questions. Book via https://calendly.com/stefaniebutland/

**Comment by complexgenome** [comment]
@stefaniebutland  Sorry no skills in this area.

**Comment by stefaniebutland** [comment]
@sariya Thanks for kicking off this activity!

**Comment by stefaniebutland** [comment]
A blog post by @Bisaloo & @Rekyt will be published July 15 outlining how they got closed captions for a community call. Will post here when published.

**Comment by stefaniebutland** [comment]
Published!

[Community Captioning of rOpenSci Community Calls](https://ropensci.org/blog/2020/07/15/subtitles/), by @Rekyt & @Bisaloo 

Now deciding how to proceed with captioning future calls. Too much time and effort expect a person to do this for free!

**Comment by stefaniebutland** [comment]
# Notes from [CSCCE](https://www.cscce.org/) Tools Trial on captioning tools. Oct 15, 2020

Played with Google Slides captions & Otter.ai
[See Collaborative notes doc with additional resources
](https://docs.google.com/document/d/1Xo3pPnjtf6c5Frzr-sF6u8wR72ApZgwrIFdTWhP6DDM/edit#)
## Google slides
- click "Present" at top right corner
- click "Captions" in box at bottom left of presentation
- captions stop if you exit presentation mode
- captions are not saved!
- a question from a participant (e.g. via zoom) is *not* captioned with any useful quality
- ppl say Google Meet has impressive captions, but apparently there's not an exportable transcript
- this is apparently also 

From Nancy Coddington
> Rev.com will give you text file, scc file and you can upload directly to YouTube or Vimeo

Naomi Penfold says she has similar use case to rOpenSci captioning Community Calls for vimeo/youtube

## Otter.ai
- must have "Live on Custom Streaming Service" turned on during Zoom
- [Otter for Teams](https://otter.ai/purchase/team) is $20/user/month if paid annually; need to have this license to use Otter Live Notes, a Zoom add-on that allows you to launch from Zoom. Participants can also view, highlight, and comment on the transcript.
- fairly accurate
- streamed transcript is at a separate link
- Otter Livenotes directly integrates with Zoom - paid version can record up to 4hrs at a time. Free Otter is limited to 40mins per recording.
- some consensus that Otter gives better quality transcript
- punctuation is good

## Thoughts
- Naomi Penfold did Otter then manual edits for closed captions: 40 minutes audio —> 10 person-minutes on Otter, 2.5 person-hours to check and edit.
- I notice that Zoom transcript (that I used for permanent captions on video) has speaker names associated with transcript pieces, but Otter does not. Really wonder how that would influence captions in a session with multiple speakers as in a panel discussion. Creates more editing work post-event.
  - update Camille Santestevan says you can manually tag speakers - Otter can differentiate between different voices so if you tag one line of text, it will attempt to find all their other speech throughout the transcript

I shared Matthias & Hugo's post - [Community Captioning of rOpenSci Community Calls](https://ropensci.org/blog/2020/07/15/subtitles/) - with the group and in their notes doc

**Comment by complexgenome** [comment]
@stefaniebutland thank you very much for massive efforts :)

**Comment by stefaniebutland** [comment]
Thanks @sariya. @Rekyt & @Bisaloo still did all the hard work! But I'm slowly trying to assimilate how we can adopt best practices without significant budget, and sharing the info I glean from others.

**Comment by stefaniebutland** [comment]
Closing this valuable issue. Glad we have so many resources on this now so we can make choices with our eyes open. 

Next call (Dec 16, 2020) I think I'll try Otter to minimize edits needed and see how the closed captions look without editing lengths of captions etc in Amara. I have the sense we can get good value from these captions without aiming for perfection. 

### Resources
- from The Center for Scientific Collaboration and Community Engagement ([CSCCE](https://www.cscce.org/)): Pratt, Katie, Santistevan, Camille, Woodley, Lou, Butland, Stefanie, & Gould van Praag, Cass. (2020, November 11). DEI Tip Sheet: Captioning, subtitles, and transcription for online meetings and events. Zenodo. http://doi.org/10.5281/zenodo.4268671
- rOpenSci blog post [Community Captioning of rOpenSci Community Calls](https://ropensci.org/blog/2020/07/15/subtitles/) by Matthias Grenié and Hugo Gruson

**Comment by Rekyt** [comment]
Thank you so much on diving deep enough on the matter so that we all get a clear view on the different possibilities!

**Comment by stefaniebutland** [comment]
Subtitles on video, and full transcript added to collaborative notes doc for Dec 2020 call on [The Wild World of Data Repositories](https://ropensci.org/commcalls/dec2020-datarepos/)
