### ISSUE TITLE
how to cite software and data

### ISSUE THREAD

**Issue by sckott** [ropensci-org/community-calls#16]
# how to cite software and data

### Who is the audience?

Everyone probably

### Why is this important?

Software and data are not well cited

### What should be covered?

- How to cite an R package
- How to cite datasets used from an R package

**Comment by stefaniebutland** [comment]
We ought to cover this content as part of other community calls.

**Comment by jananiravi** [comment]
It would be great to learn of easy & automatic ways to cite all loaded/used packages for a project.
Is this the general idea? _Give a list of packages ➡️ get the list of citations as a bib file_

**Comment by Bisaloo** [comment]
@jananiravi, here are some resources that you might like:

- [grateful: an R Package to Facilitate Citation of R Packages](https://github.com/Pakillo/grateful)
- [Automatically generate R packages citations in Rmarkdown documents](https://bookdown.org/yihui/rmarkdown-cookbook/write-bib.html)

I think there is another package with the same purpose as grateful but I can't remember the name right now. Maybe someone else will chime in.

**Comment by stefaniebutland** [comment]
Resource. 
Almarzouq (2021, March 18). Batool's Blabber: Make Your Computational Analysis Citable. Retrieved from https://batool-blabber.netlify.app/posts/2021-06-23-make-your-computational-analysis-citable/

and Batool's useR! 2021 lightning talk with similar content to that post https://youtu.be/IrV2l3qdon8

**Comment by yabellini** [comment]
We have material in blog posts about this topic.
