### ISSUE TITLE
Label-athon

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/community-calls#23]
# Virtual gathering label-athon
Virtual gathering to give developers a set time to make their packages more contributor-friendly, including:

1) Labelling issues (e.g.,  "help wanted", "good first issue") (see Issues in the [Contributing Guide](https://contributing.ropensci.org/resources.html#issues))
2) *Creating* and labelling issues specifically for outside contributors
3) Adding design plans and road maps for the package to help potential contributors better understand the coding framework and future plans
4) Adding/updating contributing guides (including set up, etc.)

### Who is the audience?
**Any** R developer with a package on an online platforms with issue trackers (ideally rOpenSci packages, but all welcome). Not restricted to packages in one domain. This activity involves developers working on their own packages.

### Why is this important?
One strength of open source software is that it can be community driven. However, developers do need to ensure their packages are contributor-friendly. When packages are created in spare time, these tasks often occupy a lower priority. Improving/increasing community contributions is a goal of rOpenSci

Getting together for a dedicated time with other developers (meeting and networking with your people) can be fun AND productive, especially now when many of us feel isolated. Who are the rOpenSci community? Are we a community if we never interact? Let's meet each other!

### What will we do?
- Meet and Greet, icebreakers
- Go into small breakout rooms to work* on our own packages and chat
- Group leaders in rooms to help with questions, keep things collegial etc.
- Mini breaks for socializing

*Work means:
  - Labelling existing issues
  - Creating and labelling small issues (e.g., check docs for typos, add a tutorial on topic X, feedback on feature Y)
  - Creating and labelling medium issues (e.g., added functionality)
  - Adding design plans and Road maps (e.g., Some ideas from ["Maintaining an R package" initial chatter](https://github.com/ropensci-org/community-calls/issues/5#issuecomment-574874270))
  - Adding/updating contributing guides

### Resources you would recommend to the audience
- Issues in the [Contributing Guide](https://contributing.ropensci.org/resources.html#issues)

**Comment by stefaniebutland** [comment]
This ~90-min issue label-athon fits super well as preparation for a comm call -hackathon #18. Not restricted to packages in one domain.  

Relates to community call Set up your package to get the most out of your community #21

**Comment by wlandau** [comment]
I think some of us could use tips and tricks to minimize manual repetition. For example, I have not found a good way to port labels from one repo to another.

**Comment by steffilazerte** [comment]
Perhaps a workflow with [`usethis::use_github_labels()`](https://usethis.r-lib.org/reference/use_github_labels.html)?

Definitely something to think about!

**Comment by wlandau** [comment]
Thanks! How did I ever live without this?

Just wrote https://github.com/wlandau/dotfiles/blob/main/helpers/label_repo.R for future repos.

**Comment by maelle** [comment]
What a nice event idea :clap: 

Should a helpful contributing guide be a pre-requisite or something that could be added to repos during the labe-athon? Especially for packages where there are some important things to know/set up (account at a developer sandbox for instance).

**Comment by steffilazerte** [comment]
The idea is that it's the developers themselves who will be adding labels, issues, contributing guides, etc. to their own packages. So it's not necessarily a pre-requisite, but definitely something that the developers could work on during the label-athon. I've added this to the list of things to work on. Good idea!

I also clarified the idea that developers work on their own packages.

**Comment by stefaniebutland** [comment]
My current thinking is that the labelathon would follow nicely after the comm call "Set up your package to get the most out of your community #21" where we can coach folks on what things to set up, and during the labelathon they take time to do them, with us around (in zoom) to answer questions.

**Comment by stefaniebutland** [comment]
First Labelathon Apr 29 has been a blast and we'll schedule more.
https://ropensci.org/events/labelathon01/

Folks can co-work on implementing some of [these recommendations](https://ropensci.org/blog/2021/04/28/commcall-pkg-community/)....or to hang out and work on their own package, but with company

## Resources for labelathon
Summary blog post: https://ropensci.org/blog/2021/04/28/commcall-pkg-community/

Landing page with video and links to resources, incl collaborative notes doc: https://ropensci.org/commcalls/apr2021-pkg-community/

**Comment by steffilazerte** [comment]
## Upcoming Labelathons!

The first labelathon on April 29th was loads of fun, and we've got three more to go!

**[May 13th](https://ropensci.org/events/labelathon02/)** (5pm Pacific)

-  [Registration Encouraged!](https://form.jotform.com/211236716589260)

**[May 27th](https://ropensci.org/events/labelathon03/)** (9am Pacific)

-  [Registration Encouraged!](https://form.jotform.com/211236537172249)
 
**[June 10th](https://ropensci.org/events/labelathon04/)** (5pm Pacific)

-  [Registration Encouraged!](https://form.jotform.com/211236201763243)

**Comment by stefaniebutland** [comment]
Success!
We're turning these into monthly social co-working / office hours sessions, at alternating times to satisfy different timezones.
