### ISSUE TITLE
R and open and reproducible research in governments

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/community-calls#26]
# Topic

### Who is the audience?
People working in all levels of government in different countries. Many of these folks are thinking about and working on changing internal work culture so lessons learned are applicable to any group - like a company, an academic research lab or department for example.

### Why is this important?
Many in the rOpenSci community have been sharing their experiences, successes, and challenges in making data science in their government orgs more reproducible and open. rOpenSci might be a good third-party to convene the discussion and forge connections.

### Suggested speakers or contributors
- UK federal gov: @matt-dray - contributed use cases for drake, magick, rtweet, [example](https://discuss.ropensci.org/t/can-drake-rap-promoting-drake-for-pipeline-management-in-uk-government/1841)
- UK local gov: Henry Partridge - contributed [use cases](https://discuss.ropensci.org/t/promoting-r-and-ropensci-packages-in-uk-local-government/1776), https://www.trafforddatalab.io/
- British Columbia gov: @boshek @ateucher @stephhazlitt (former)
- USGS: @ldecicco-USGS
- Julie Lowndes @jules32 might have ideas based on gov participants in Openscapes cohorts.

**Comment by maelle** [comment]
Resource from France, in French, by @dianebeldame, @colinfay & @statnmap: https://rdes_dreal.gitlab.io/propre/

**Comment by matt-dray** [comment]
Also from UK government: @sebastian-fox is behind [the rOpenSci package {fingertipsR}](https://docs.ropensci.org/fingertipsR/) and will have some great insight on challenges.

**Comment by swmpkim** [comment]
Possible speaker from US EPA: @jhollist

**Comment by stefaniebutland** [comment]
How could I forget @jhollist! Especially as he's a new editor for software peer review. Thanks @swmpkim. Reminds me that @adamhsparks, another new editor is now at [gov ](https://www.wa.gov.au/organisation/department-of-primary-industries-and-regional-development)in Western Australia.

**Comment by jules32** [comment]
Hi! This will be a great community call! 

A few more R folks in gov:
@eeholmes at NOAA (US) is fantastic: https://twitter.com/eeholm. See her most recent tweets about her release on CRAN and experiences with Cloud and Python too
@martinjeanphd at Environment and Climate Change Canada is as well: https://twitter.com/martinjeanphd he works with https://twitter.com/Monsauce (PREreview and other open science efforts)

Also of potential interest: we're leading a [Openscapes session at ESIP](https://2022esipjanuarymeeting.sched.com/event/qkp5/better-science-for-future-us-planning-for-the-year-of-open-science) with US gov folks from NASA, NOAA, and EPA if folks are attending - we can share notes afterwards too

**Comment by jhollist** [comment]
Thanks for tagging me in, @swmpkim!  I am certainly interested if timing allows.

Another possibility that comes to mind is @ateucher with BC gov.

**Comment by adamhsparks** [comment]
I'm surely interested as timezones and time allow!

Also, there's a heap of us here in Oz in government/public policy positions, so many in fact that we have our own Slack workgroup and a Twitter list too, [runapp](https://runapp-aus.github.io/runapp_website/).

**Comment by matt-dray** [comment]
@ChrisBeeley and @Lextuga007 of the UK's Nottinghamshire Healthcare NHS Trust ([GitHub](https://cdu-data-science-team.github.io/team-blog/), [website](https://github.com/nhs-r-community)) are doing stellar work to create and promote open and transparent R products. They're involved in the excellent NHS-R Community ([GitHub](https://github.com/nhs-r-community), [website](https://nhsrcommunity.com/)) for R promotion/workshops/tutorials/best practice across the NHS, as is @johnmackintosh.

**Comment by ChrisBeeley** [comment]
Thanks Matt, very interested in this :relaxed:

**Comment by boshek** [comment]
Sounds fun!

**Comment by johnmackintosh** [comment]
Thanks @matt-dray ,  happy to contribute  :)

**Comment by stephhazlitt** [comment]
This will be a great call! @reikookamoto is an active open data science champion in bcgov who might be interested in this.

**Comment by sebastian-fox** [comment]
> Also from UK government: @sebastian-fox is behind [the rOpenSci package {fingertipsR}](https://docs.ropensci.org/fingertipsR/) and will have some great insight on challenges.

Yes - really interested in this

**Comment by eeholmes** [comment]
I would definitely be interested! I am part of [RGovys](https://rgovys.github.io/) a R-Consortium working group that is a project of the Interagency R-User Group, a R UG spanning all the US federal agencies. I am also leading [NMFS Openscapes](https://github.com/nmfs-openscapes) which supports open science efforts and groups in NOAA Fisheries.

**Comment by linogaliana** [comment]
In France, there has been an initiative called `utilitR` that emerged from Insee (French national institute) and opensourced. It involved around 30 contributors from various administrations.

# Objective

The objective is to propose a documentation based on opendata (using Insee's data from `doremifasol` package) that proposes, for a series of standard data tasks (importing and visualising data, communication...), some state of the art packages and advices. This documentation recommends some package for each tasks, gives some advices derived from experienced users... 

An important aspect of this documentation is an emphasis on the subjects of reproductibility and perennity. We launched the initiative to help users being more aware on good practices. We want people to be aware of [Ropensci guide of good practice](https://devguide.ropensci.org/building.html) and [tidyverse styling guide](https://style.tidyverse.org/). We will propose a guide that proposes, at the same time, some Python recommendations because we want projects made by our administrations to be easily converted from `Python` to `R` or vice-versa.

By the way, everything is in French to help users that are not fluent in English.

From day 1, everything has been opensourced and developped as websites built with `RMarkdown`. We propose other outputs (e.g. possibility to print each page as `PDF`, thanks @rlesur). Everything has been thought to be updated in continuous to account for the evolution of `R` language.

# Links

- Main documentation : https://www.book.utilitr.org/ ([github repo here](https://github.com/InseeFrLab/utilitR))
- Main entry point : [www.utilitr.org/](https://www.utilitr.org/)
- Guide of good practice (will be updated): https://www.pratiques.utilitr.org
- Current discussions regarding the update of the guide of good practices: https://github.com/InseeFrLab/utilitR/issues/388

**Comment by MaelTheuliere** [comment]
> Resource from France, in French, by @DianeBeldame, @ColinFay & @statnmap: https://rdes_dreal.gitlab.io/propre/

An for a  concrete application, you can see https://gitlab.com/rdes_dreal/propre.rpls 
An R package that produce reproductible reports on social housing for all french regions


Also a brochure that explain the process : https://dreal.statistiques.developpement-durable.gouv.fr/parc_social/2020/www/export_demarchePropre.pdf

For more info, please see @jengelaere @MurielleL

**Comment by MaelTheuliere** [comment]
Another french project, gouvdown} that let you write R Markdown documents and make ggplot graphics which comply with the French government design system.

repo : https://github.com/spyrales/gouvdown
authors: @RLesur @tvroylandt @MaelTheuliere

**Comment by matt-dray** [comment]
I should tease out something from one of my [submitted rOpenSci use cases](https://discuss.ropensci.org/t/can-drake-rap-promoting-drake-for-pipeline-management-in-uk-government/1841): 'Reproducible Analytical Pipelines' (RAP).

RAP is a grassroots movement  in the UK government that promotes code-based workflows for statistical publications, with emphasis on reproducibility, version control and testing. [This blog has a decent overview](https://joinup.ec.europa.eu/collection/study-data-analytics-member-states-and-citizens/discussion/blog-4-uk-reproducible-analytical-pipelines-rap). The community includes ~500 people in our Slack channel, from federal and local organisations; nominated departmental champions; and meet-ups to discuss technical and cultural approaches.

There are various members of our Office for National Statistics (ONS) or Government Statistical Service (GSS) that could talk or provide support, like @alexander-newton.

**Comment by stefaniebutland** [comment]
@dickoa mentioned relevance of this topic to his work at [UNHCR](https://www.unhcr.org/).

**Comment by stefaniebutland** [comment]
Tagging you @wmlandau since many of these folks use your workflow packages and some incl @matt-dray have submitted use cases for them

**Comment by matt-dray** [comment]
I think @wlandau is Will's GitHub handle

**Comment by dickoa** [comment]
Thanks @stefaniebutland, can't wait for this community calls. It's really cool to see all the people in this thread whose work were influential to the work we did and currently doing with some UNHCR colleagues (@vidonne, @galalH, @Edouard-Legoupil, etc)  

Here are some new WIP packages we're currently working on (inspired by the DREAL, RAP and others similar framework)
https://github.com/vidonne/unhcrthemes/
https://github.com/vidonne/unhcrdown
https://github.com/unhcr/unhcrdatapackage

Also want to use this opportunity really to thank everyone in this thread for the work (documentation included) they did on reproducible research, and I look forward to attending this community call.

**Comment by Edouard-Legoupil** [comment]
Thanks @dickoa !
Maybe interesting to get some colleagues from World-Bank - see [DIME Research Reproducibility Standards](https://github.com/worldbank/dime-standards/tree/master/dime-research-standards/pillar-3-research-reproducibility) from @kbjarkefur , @luisesanmartin and @luizaandrade  

Also to mention that in order to change the culture, it requires to influence the way money is being used - Inspiring ideas here on the  [The Role of Funding Agency Policy](http://stodden.net/icerm_report.pdf#page=5)!

**Comment by reikookamoto** [comment]
Thanks for the tag @stephhazlitt 😄 

Looping @henry-ngo into the conversation as well

**Comment by henry-ngo** [comment]
Thanks @reikookamoto , happy to be involved too. 

And to tag two other names in Canadian federal govt (Fisheries and Oceans Canada), in case they are interested:
@seananderson
@andrew-edwards

**Comment by alexander-newton** [comment]
Thanks for tag @matt-dray . I'd be happy to contribute to any talks here. My team track [use of coding in analysis in UK central gov](https://best-practice-and-impact.github.io/CARS-3/). We also support the community and work with senior leadership to get buy-in.

**Comment by luizaandrade** [comment]
Thank you for thinking of us @Edouard-Legoupil! We've been trying to push the transparency and reproducibility agenda within our research department at the World Bank and in the governments we work with for a few years and would be happy to share our thoughts and experiences. 

We have also recently released a handbook ([free PDF here](https://openknowledge.worldbank.org/handle/10986/35594)) on using data for development research that may be of interest.

**Comment by mpaulacaldas** [comment]
Hello! I came over from the rOpenSci newsletter. With @Julie-byte-22 (and previously, @philipchan-oecd), I co-lead the internal R/Python/Git Community of Practice (300+ members) at the [OECD](https://www.oecd.org/about/), an international organisation providing policy advice and international statistics. 

I would love to follow the discussions from this group, as an R user, to gather ideas and use-cases to help improve our internal processes, but also to see if I could help connect some of the people from this group with those at OECD working with NSOs or statistical government bodies. Already I see some that have already presented for our internal user group, like @luizaandrade, @linogaliana and @RLesur 👋 

Within the OECD, we are seeing a lot of interest in quarto/RMarkdown, ggplot2 theming and internal package development, but most of our work in this is still hidden behind our internal Gitlab server. Hopefully we can see this change in the future!

**Comment by yabellini** [comment]
Thanks so much @mpaulacaldas for comment on this idea. We have a lot of interest in this topic, so I will start organizing the Comm Call :-) 
Expect some messages from me.

**Comment by maelle** [comment]
resource: https://www.rostrum.blog/2023/06/13/panic-in-the-toolshed/ by @matt-dray

**Comment by Lextuga007** [comment]
I'll be following Matt after the talks today with this https://github.com/nhs-r-community/NHSRpresentations/tree/main/20230613-government-toolshed to promote how NHS-R Community can help be a holding place/playground for work across the Civil Service and Public Sector (which are slightly different things in the UK but we can learn and work together 😃 ).

**Comment by andrew-edwards** [comment]
In case it's of interest, colleagues (in academia) and I wrote an e-book that includes a chapter on getting started with Git and GitHub:   https://www.quantitative-biology.ca/git-and-github.html. Also one on R Markdown: https://www.quantitative-biology.ca/r-markdown.html. 

I'm a scientist at Fisheries and Oceans Canada. Several years ago a co-worker with a computer science background got some of us started with Git, and we later gave a national workshop that got more people using it across our organization. The e-book evolved from the workshop materials, and includes examples and videos. It's aimed at biologists (or really anyone without a computer science degree), and avoids some of the tech-heavy jargon that people come across when first trying to learn Git. Many of us now use Git daily in our work.

**Comment by yabellini** [comment]
Update: we will have this comm call during October.  We have a great lineup of speakers. I will share more info soon. :-) 
Now I'm organizing June and July Comm Call.

**Comment by Lextuga007** [comment]
@andrew-edwards Yes! Very interested - thanks so much for sharing! I've been putting together some Intro to [Git and GitHub slides ](https://github.com/nhs-r-community/intro-git-github#introduction-to-git-and-github) but using R and R Studio, particularly {usethis} and {gert}. I've been like a magpie though with resources so this is really welcome 😃

**Comment by stefaniebutland** [comment]
@dangowans @sfirke my municipal gov GitHub friends! Check out this community call planned for ~Oct 2023. 

shoutout to my hometown and @dangowans "[most active and second most starred Canadian municipality on GitHub](https://cityssm.github.io/municipal-github-rankings/)."

**Comment by yabellini** [comment]
Please schedule October 31 at 16.00 UTC for this Community Call !!
More details soon :-)

**Comment by yabellini** [comment]
📣 [Community Call] R in Government

With @luizaandrade, @KarHarker, @dickoa and Pablo Tiscornia

🕓 __Tuesday, 31 October 2023 16:00 UTC__

We invite you to learn about the challenges and lessons learned from our panelists and attendees in their efforts to make their government data, processes, and analyses more open and reproducible.

📌 More info + join the event here: https://ropensci.org/commcalls/oct2023-government/

**Comment by yabellini** [comment]
Thanks so much @luizaandrade, @KarHarker, @dickoa and @pablotis for today community call 🙏 
Also, thanks so much to all the attendees. We will update all the resources and video next week.  We will let you all know here when the material is ready.

**Comment by yabellini** [comment]
Hello, the video with subtitles, the shared document with the transcript and other resources are published in our webpage. https://ropensci.org/commcalls/oct2023-government/

One more time, thank you so much to [Luíza Andrade](https://ropensci.org/author/lu%C3%ADza-andrade/), [Karly Harker](https://ropensci.org/author/karly-harker/), [Ahmadou Dicko](https://ropensci.org/author/ahmadou-dicko/) and [Pablo Tiscornia](https://ropensci.org/author/pablo-tiscornia/).
