### ISSUE TITLE
Translation processes on packages and documentation

### ISSUE THREAD

**Issue by yabellini** [ropensci-org/community-calls#28]
# Topic

### Who is the audience?
Software developers and users.

### Why is this important?
Having multi-language support would lower the language barrier in the use of packages and software.
It would be very useful to discuss with the community what kind of support and tools we need in order to have documentation and packages in various languages.

### What should be covered?
Why translate
Tools and guideline to translate
how to work on translation maintenance

### Suggested speakers or contributors
Kun Ren -  how a group he worked with translated data.table's documentation and code into Chinese.
Michael Chirico - how to translate error messages on base R

### Resources you would recommend to the audience
- useR! 2021 Translation base R Tutorial

**Comment by steffilazerte** [comment]
@maelle and I also had a conversation on Slack with some others about how to maintain dual language documentation with pkgdown. Useful?

**Comment by yabellini** [comment]
We did this two comm calls: https://ropensci.org/commcalls/nov2023-multilingual/, https://ropensci.org/commcalls/nov2023-multilenguaje/

When Elio made some progress with they project we cna have a comm call about it.
