### ISSUE TITLE
How to cite ropensci-org community-calls repo?

### ISSUE THREAD

**Issue by aranas** [ropensci-org/community-calls#29]
I really liked how you have set up your repo for collaboratively organising the community calls. I have used your repo as an example for modelling our own community around a digital twin research community at the Alan Turing Institute ([see repo here](https://github.com/alan-turing-institute/tric-dt/tree/main/Seminars)).

I would like to cite your README, do you have a preferred way in which I could reference it?

**Comment by yabellini** [comment]
So glad this is useful! Thank you for letting us know and for asking.  What about something like this:

> ## Acknowledgment 
> 
> We want to acknowledge the inspiration we received from a similar resource: [rOpenSci's Community Call public ideas repository](https://github.com/ropensci-org/community-calls/blob/master/README.md).
> 

Also, we will be very grateful if you can share this as a use case in our forum: https://discuss.ropensci.org/c/usecases/10
